# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0002_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=40)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.Finance')),
            ],
        ),
    ]
