# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0003_savingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.Month'),
        ),
    ]
