# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0004_auto_20190328_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='savings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='save.SavingPlan'),
        ),
    ]
