# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0005_finance_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
    ]
