# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0007_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='amount',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='extracash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
