# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0008_auto_20190328_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='months',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='save.Month'),
        ),
    ]
