# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('save', '0010_auto_20190328_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50, null=True)),
                ('expenses', models.CharField(max_length=100)),
                ('salaryearned', models.CharField(max_length=1000)),
                ('extracash', models.CharField(max_length=100, null=True)),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.Month')),
                ('savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.SavingPlan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
